### ISSUE TITLE
required version to compile cuda code

### ISSUE THREAD

**Issue by charliewang789** [sunwj/CAR#11]
can someone post a workable version of pytorch, cuda, c++ that can compile the code?

**Comment by GlockPL** [comment]
Worked for me on pytorch 1.4.0. I tested it on google colab.

**Comment by davertor** [comment]
How did you make it work @GlockPL ??? I tried installing pytorch 1.4.0 in colab and I have the following error 

CUDA error at adaptive_gridsampler_kernel.cu:76 code=209(cudaErrorNoKernelImageForDevice) "cudaGetLastError()"

**Comment by GlockPL** [comment]
This is my code from colab:
`!pip install torch==1.4.0 torchvision==0.5.0`
`!git clone https://github.com/sunwj/CAR.git`
`%cd ./CAR/
!ls`
`%cd adaptive_gridsampler/
!ls`
`!python3 setup.py build_ext --inplace`
Last part is crucial because you need to compile this adaptive_gridsampler which is the reason why you get this error.
