### ISSUE TITLE
Error when running the code

### ISSUE THREAD

**Issue by treammm** [sunwj/CAR#7]
Hi @sunwj, thanks for open sourcing the code!

I tried to run it and have successfully setup the dependencies. However, when running run.py, it gives this error message
`CUDA error at adaptive_gridsampler_kernel.cu:76 code=48(cudaErrorNoKernelImageForDevice) "cudaGetLastError()"`

And the output is a black image and with (Mean PSNR: 6.53; Mean SSIM: 0.1514). Wondering if there's a CPU version just for model inference? That would be less likely to encounter this kind of environmental error!

**Comment by acupofespresso** [comment]
I fixed the error,   refer this link 

http://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/

first  modify nvcc_args   in adaptive_gridsampler/setup.py

nvcc_args = [
    '-gencode', 'arch=compute_52,code=sm_52',  # I Added this line for NVIDIA-SMI 450.66       Driver Version: 450.66       CUDA Version: 11.0,  GeForce GTX 970  Card
    '-gencode', 'arch=compute_60,code=sm_60',
    '-gencode', 'arch=compute_61,code=sm_61',
    '-gencode', 'arch=compute_70,code=sm_70',
    '-gencode', 'arch=compute_70,code=compute_70'
]

then build ext

python3 setup.py build_ext --inplace
